---
title: "Lab_4A"
output: html_document
author: Alina Sequeira
date: September 19, 2020
---
```{r}
library(tidyverse)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
install.packages("tidyverse")
```

## Plotting with ggplot2
```{r}
# Aesthetic mapping

ggplot(data = surveys_complete, mapping = aes(x = weight, y = hindfoot_length))
```
```{r}
# Add a geom - graphical representations

ggplot(data = surveys_complete, aes(x = weight, y = hindfoot_length)) +
  geom_point()
```
```{r}
# Assign plot to a variable

surveys_plot <- ggplot(data = surveys_complete, mapping = aes(x = weight, y = hindfoot_length))

#Draw the plot

surveys_plot + geom_point()
```

## Challenge 1
```{r}
library(hexbin)
```
```{r}
# Hexagonal bin plot - better representation of data with a large num of observations

surveys_plot +
  geom_hex()
```

## Building Plots Iteratively
```{r}
ggplot(data = surveys_complete, aes(x = weight, y = hindfoot_length)) + 
  geom_point()
```
```{r}
# transparent(alpha) to avoid overplotting

ggplot(data = surveys_complete, aes(x = weight, y = hindfoot_length)) +
  geom_point(alpha = 0.1)
```
```{r}
# add colors for all the points

ggplot(data = surveys_complete, mapping = aes(x = weight, y = hindfoot_length)) +
  geom_point(alpha = 0.1, color = "blue")
```
```{r}
# color each speices in a plot differently / aes(color = species_id)

ggplot(data = surveys_complete, mapping = aes(x = weight, y = hindfoot_length)) +
  geom_point(alpha = 0.1, aes(color = species_id))
```

## Challenge 2
```{r}
ggplot(data = surveys_complete, mapping = aes(x = species_id, y = weight)) +
  geom_point(aes(color = plot_type))
```

## Boxplot
```{r}
# visualize the distribution of weight within each species

ggplot(data = surveys_complete, mapping = aes(x = species_id, y = weight)) +
geom_boxplot()
```
```{r}
# Add points to the boxplot - better idea of num of measurements and distribution
# use geom_jitter()

ggplot(data = surveys_complete, mapping = aes(x = species_id, y = weight)) + 
  geom_boxplot(alpha = 0) +  #makes bg transparent
  geom_jitter(alpha = 0.3, color = "tomato")
```

## Challenge 3
```{r}
# replace boxplot with violin plot - shape (of the density of point) is drawn
# use geom_violin()

ggplot(data = surveys_complete, mapping = aes(x = species_id, y = weight)) + 
  geom_violin()
```
```{r}
# Represent weight on the log10 scale - better distribute the obvs
# use scale_y_log10()

ggplot(data = surveys_complete, mapping = aes(x = species_id, y = weight)) + 
  geom_violin() +
  scale_y_log10()
```
```{r}
# Distribution of hindfoot_length within each species

ggplot(data = surveys_complete, mapping = aes(x = species_id, y = hindfoot_length)) +
  geom_boxplot(alpha = 0) +
  geom_jitter(alpha = 0.3, aes(color = plot_id))
```
```{r}
# change plot_id to a factor

plot_id <- factor()

ggplot(data = surveys_complete, mapping = aes(x = species_id, y = hindfoot_length)) +
  geom_boxplot(alpha = 0) +
  geom_jitter(alpha = 0.3, aes(color = plot_id))
```

## Plotting Time Series Data
```{r}
yearly_counts <- surveys_complete %>% 
  count(year,genus)
```
```{r}
ggplot(data = yearly_counts, aes(x = year, y = n))+
  geom_line()
```
```{r}
# draw a line for each genus
ggplot(data = yearly_counts, aes(x= year, y = n, group = genus))+
  geom_line()
```
```{r}
# add color, automatically groups the data
ggplot(data = yearly_counts, aes(x = year, y = n, color = genus)) +
  geom_line()
```
```{r}
yearly_counts %>% 
  ggplot(mapping = aes(x = year, y = n, color = genus))+
  geom_line()
```
```{r}
#use pipe to link data manipulation to a data visual
yearly_counts_graph <- surveys_complete %>% 
  count(year,genus) %>% 
  ggplot(mapping = aes(x= year, y = n, color = genus)) +
  geom_line()

yearly_counts_graph
```
```{r}
# splits one plot into multiple plots based on a factor in the dataset (ex: species)
ggplot(data = yearly_counts, aes(x=year, y=n))+
  geom_line()+
  facet_wrap(facets = vars(genus))
```
```{r}
#split the line in each plot by sex of each individual measured
yearly_sex_counts <- surveys_complete %>% 
  count(year, genus, sex)
```
```{r}
#split further with color
ggplot(data = yearly_sex_counts, mapping = aes(x = year, y = n, color = sex))+
  geom_line()+
  facet_wrap(facets=vars(genus))
```
```{r}
#facet both by sex and genus
ggplot(data = yearly_sex_counts, 
       mapping = aes(x=year, y=n, color=sex)) +
  geom_line()+
  facet_grid(rows = vars(sex), cols = vars(genus))
```
```{r}
# organize panels only by rows (or by columns)
## one column, facet by rows
ggplot(data = yearly_sex_counts,
       mapping = aes(x=year, y=n, color=sex))+
  geom_line()+
  facet_grid(rows=vars(genus))
```
```{r}
# one row, facet by column
ggplot(data = yearly_sex_counts,
      mapping = aes(x = year, y = n, color = sex)) +
  geom_line()+
  facet_grid(cols=vars(genus))
```

## ggplot2 Themes
```{r}
ggplot(data = yearly_sex_counts,
       mapping = aes(x=year, y=n, color=sex))+
  geom_line()+
  facet_wrap(vars(genus))+
  theme_bw()
```

## Challenge 4
```{r}
yearly_weight<- surveys_complete %>% 
  group_by(year,species_id) %>% 
  summarize(avg_weight= mean(weight))
```
```{r}
ggplot(data = yearly_weight, 
       mapping = aes(x=year, y=avg_weight))+
  geom_line()+
  facet_wrap(vars(species_id))+
  theme_bw()
```

## Customization
```{r}
#add titles & axes labels
ggplot(data = yearly_sex_counts, aes(x=year, y=n, color=sex)) +
  geom_line()+
  facet_wrap(vars(genus))+
  labs(title = "Observed genera through time",
       x = "Year of observation",
       y = "Number of individuals")+
  theme_bw()
```
```{r}
#improve readability by increasing font size
ggplot(data = yearly_sex_counts, mapping = aes(x = year, y = n, color = sex)) +
    geom_line() +
    facet_wrap(vars(genus)) +
    labs(title = "Observed genera through time",
        x = "Year of observation",
        y = "Number of individuals") +
    theme_bw() +
    theme(text=element_text(size=16))
```
```{r}
# customize axis color, size, and angle
# use strip.text to italicize genus name
ggplot(data = yearly_sex_counts, mapping = aes(x = year, y = n, color = sex)) +
    geom_line() +
    facet_wrap(vars(genus)) +
    labs(title = "Observed genera through time",
        x = "Year of observation",
        y = "Number of individuals") +
    theme_bw() +
    theme(axis.text.x = element_text(colour = "grey20", size = 12, angle = 90, hjust=0.5, vjust=0.5),
                                    axis.text.y = element_text(colour = "grey20", size = 12),
                                    strip.text = element_text(face ="italic"),
                                    text = element_text(size=16))
```
```{r}
# save changes to a default theme to easily apply it to other plots you create
grey_theme <- theme(axis.text.x = element_text(colour="grey20", size = 12, 
                                               angle = 90, hjust = 0.5, 
                                               vjust = 0.5),
                    axis.text.y = element_text(colour = "grey20", size = 12),
                    text=element_text(size = 16))

ggplot(surveys_complete, aes(x = species_id, y = hindfoot_length)) +
    geom_boxplot() + grey_theme #created default theme
```

## Challenge 5
```{r}
ggplot(data = yearly_sex_counts, mapping = aes(x = year, y = n, color = sex)) +
    geom_line() +
    facet_wrap(vars(genus)) +
    labs(title = "Observed genera through time",
        x = "Year of observation",
        y = "Number of individuals",
        color = "Sex of individual") +
    scale_color_brewer(palette ="Set1", labels = c("Female","Male"))+
    theme_light() +
    theme(axis.text.x = element_text(colour = "grey20", size = 12, angle = 90, hjust=0.5, vjust=0.5),
                                    axis.text.y = element_text(colour = "grey20", size = 12),
                                    strip.text = element_text(face ="italic"),
                                    text = element_text(size=16))
```

## Arranging and Exporting Plots
```{r}
library(gridExtra)
```
```{r}
spp_weight_boxplot <- ggplot(data = surveys_complete, 
                             aes(x = species_id, y = weight)) +
  geom_boxplot() +
  labs(x = "Species", 
       y = expression(log[10](Weight))) +
  scale_y_log10() + 
  labs()

spp_count_plot <- ggplot(data = yearly_counts, 
                         aes(x = year, y = n, color = genus)) +
  geom_line() + 
  labs(x = "Year", y = "Abundance")

grid.arrange(spp_weight_boxplot, spp_count_plot, ncol = 2, widths = c(4, 6))
```
```{r}
my_plot <- ggplot(data = yearly_sex_counts, 
                  aes(x = year, y = n, color = sex)) +
    geom_line() +
    facet_wrap(vars(genus)) +
    labs(title = "Observed genera through time",
        x = "Year of observation",
        y = "Number of individuals") +
    theme_bw() +
    theme(axis.text.x = element_text(colour = "grey20", size = 12, angle = 90,
                                     hjust = 0.5, vjust = 0.5),
          axis.text.y = element_text(colour = "grey20", size = 12),
          text = element_text(size = 16))

ggsave("name_of_file.png", my_plot, width = 15, height = 10)

## This also works for grid.arrange() plots
combo_plot <- grid.arrange(spp_weight_boxplot, spp_count_plot, ncol = 2, 
                           widths = c(4, 6))

```
```{r}
ggsave("combo_plot_abun_weight.png", combo_plot, width = 10, dpi = 300)
```



