---
title: "Lab 3A"
output: html_document
author: Alina Sequeira
date: September 13, 2020
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}
download.file(url="https://ndownloader.figshare.com/files/2292169", destfile = "data/portal_data_joined.csv")
```

```{r}
surveys <- read.csv("data_raw/portal_data_joined.csv")
```

```{r}
head(surveys)
```

```{r}
str(surveys)
```

## Challenge 1
```{r}
ncol(surveys)
```
```{r}
nrow(surveys)
```
```{r}
length(summary(surveys[ ,"species_id"]))
```

```{r}
## * class: data frame
## * how many rows: 34786
## * how many columns: 13
## * how many species: 3
```

## Indexing and Subsetting Data Frames
```{r}
# first element in the first column of the data frame (as a vector)
surveys[1, 1]
```
```{r}
# first element in the 6th column (as a vector)
surveys[1, 6] 
```
```{r}
# first column of the data frame (as a vector)
surveys[, 1]  
```

## Challenge 2
```{r}
## 1.
surveys_200 <- surveys[200, ]
## 2.
# Saving `n_rows` to improve readability and reduce duplication
n_rows <- nrow(surveys)
surveys_last <- surveys[n_rows, ]
## 3.
surveys_middle <- surveys[n_rows / 2, ]
## 4.
surveys_head <- surveys[-(7:n_rows), ]
```

## Factors
```{r}
sex <- factor(c("male", "female", "female", "male"))
levels(sex)
```
```{r}
nlevels(sex)
```
```{r}
sex # current order
```
```{r}
sex <- factor(sex, levels = c("male", "female"))
sex # after re-ordering
```

## Converting Factors
```{r}
as.character(sex)
```
```{r}
year_fct <- factor(c(1990, 1983, 1977, 1998, 1990))
as.numeric(year_fct)               # Wrong!
```
```{r}
as.numeric(as.character(year_fct)) # Works...
```
```{r}
as.numeric(levels(year_fct))[year_fct]    # The recommended way.
```

## Renaming Factors
```{r}
## bar plot of the number of females and males captured during the experiment:
plot(as.factor(surveys$sex))
```
```{r}
sex <- factor(surveys$sex)
head(sex)
```
```{r}
levels(sex)
```
```{r}
levels(sex)[1] <- "undetermined"
levels(sex)
```
```{r}
head(sex)
```

## Challenge 3
```{r}
##rename "F" and “M” to “female” and “male” respectively.
levels(sex)[2:3] <- c("female", "male")

##can you recreate the barplot such that “undetermined” is last (after “male”)?
sex <- factor(sex, levels = c("female", "male", "undetermined"))
plot(sex)
```

## Using stringsAsFactors = FALSE
```{r}
## Compare the difference between our data read as `factor` vs `character`.
surveys <- read.csv("data_raw/portal_data_joined.csv", stringsAsFactors = TRUE)
str(surveys)
```
```{r}
surveys <- read.csv("data_raw/portal_data_joined.csv", stringsAsFactors = FALSE)
str(surveys)
```
```{r}
## Convert the column "plot_type" into a factor
surveys$plot_type <- factor(surveys$plot_type)
```

## Challenge 4
```{r}
##Part 1
animal_data <- data.frame(
          animal = c("dog", "cat","sea cucumber", "sea urchin"),
          feel = c("furry","furry", "squishy", "spiny"),
          weight = c(45, 8, 1.1, 0.8)
          )

##Part 2
country_climate <- data.frame(
       country = c("Canada", "Panama", "South Africa", "Australia"),
       climate = c("cold", "hot", "temperate", "hot/temperate"),
       temperature = c(10, 30, 18, 15),
       northern_hemisphere = c(TRUE, TRUE, FALSE, FALSE),
       has_kangaroo = c(FALSE, FALSE, FALSE, TRUE)
       )
str(country_climate)
```

## Formatting Dates
```{r}
str(surveys)
```
```{r}
library("lubridate")
```
```{r}
my_date <- ymd("2015-01-01")
str(my_date)
```
```{r}
my_date <- ymd(paste("2015","1","1", sep = "-"))
str(my_date)
```
```{r}
paste(surveys$year, surveys$month, surveys$day, sep = "-")
```
```{r}
surveys$date <- ymd(paste(surveys$year, surveys$month, surveys$day, sep = "-"))
```
```{r}
str(surveys)
```
```{r}
summary(surveys$date)
```
```{r}
missing_dates <- surveys[is.na(surveys$date), c("year", "month", "day")]

head(missing_dates)
```

