---
title: "Lab_5A"
output: html_document
author: Alina Sequeira
date: 9-21-20
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(dplyr)
```
```{r}
Confirmed_State_3_13 <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-13-2020.csv")) %>%
  rename(Country_Region = "Country/Region", Province_State = "Province/State") %>% 
  filter (Country_Region == "US") %>% 
  group_by(Province_State, Country_Region) %>% 
  summarise(Confirmed = sum(Confirmed)) 
```
```{r}
str(Confirmed_State_3_13)
```
```{r}
Confirmed_State_9_13 <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/09-13-2020.csv")) %>% 
  filter (Country_Region == "US") %>% 
  group_by(Province_State, Country_Region) %>% 
  summarise(Confirmed = sum(Confirmed)) 
```
```{r}
str(Confirmed_State_9_13)
```
```{r}
setdiff(Confirmed_State_9_13$Province_State, Confirmed_State_3_13$Province_State)
```
```{r}
Confirmed_State_9_13 <- Confirmed_State_9_13 %>% 
  filter(Province_State != "Recovered") 
```
```{r}
Confirmed_State_3_13_9_13_joined <- full_join(Confirmed_State_3_13,
      Confirmed_State_9_13, by = c("Province_State"))
head(Confirmed_State_3_13_9_13_joined)
```
```{r}
tail(Confirmed_State_3_13_9_13_joined, 5)
```
```{r}
which(is.na(Confirmed_State_3_13_9_13_joined))
```
```{r}
Confirmed_State_3_13_9_13_joined <- full_join(Confirmed_State_3_13,
      Confirmed_State_9_13, by = c("Province_State")) %>% 
      rename(Confirmed_3_13_2020 = "Confirmed.x", Confirmed_9_13_2020 = "Confirmed.y") %>% 
      select(-Country_Region.x, -Country_Region.y) %>% 
      replace_na(list(Confirmed_3_13_2020 = 0))
head(Confirmed_State_3_13_9_13_joined)
```
```{r}
which(is.na(Confirmed_State_3_13_9_13_joined))
```
```{r}
Confirmed_State_3_13_9_13_joined_long <- Confirmed_State_3_13_9_13_joined %>% 
              pivot_longer(-c(Province_State),
                            names_to = "Date", values_to = "Confirmed")
```
```{r}
# to adjust figure size {r, fig.width = 5, fig.height = 10}
ggplot(Confirmed_State_3_13_9_13_joined_long, aes(x = Confirmed,  y = Province_State))  + 
    geom_point(aes(color = Date)) 
```
## Working with Time Series Data
```{r}
time_series_confirmed <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv")) %>%
  rename(Province_State = "Province/State", Country_Region = "Country/Region")
```
```{r}
head(time_series_confirmed)
```
```{r}
time_series_confirmed_long <- time_series_confirmed %>% 
               pivot_longer(-c(Province_State, Country_Region, Lat, Long),
                            names_to = "Date", values_to = "Confirmed") 
```
```{r}
head(time_series_confirmed_long)
```
```{r}
download.file(url="https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv", 
               destfile = "data/time_series_covid19_deaths_global.csv")
```
```{r}
time_series_deaths <- read_csv("data/time_series_covid19_deaths_global.csv")%>%
  rename(Province_State = "Province/State", Country_Region = "Country/Region")
```
```{r}
time_series_deaths_long <- time_series_deaths %>% 
               pivot_longer(-c(Province_State, Country_Region, Lat, Long),
                            names_to = "Date", values_to = "Deaths") 
head(time_series_deaths_long)
```
```{r}
time_series_confirmed_long <- time_series_confirmed_long %>% 
  unite(Key, Province_State, Country_Region, Date, sep = ".", remove = FALSE)
head(time_series_confirmed_long)
```
```{r}
time_series_deaths_long <- time_series_deaths_long %>% 
  unite(Key, Province_State, Country_Region, Date, sep = ".") %>% 
  select(Key, Deaths)
```
```{r}
time_series_long_joined <- full_join(time_series_confirmed_long,
              time_series_deaths_long, by = c("Key")) %>% 
              select(-Key)
head(time_series_long_joined)
```
```{r}
which(is.na(time_series_long_joined$Confirmed))
```
```{r}
which(is.na(time_series_long_joined$Deaths))
```
```{r}
library(lubridate)
```
```{r}
time_series_long_joined$Date <- mdy(time_series_long_joined$Date)
```
```{r}
time_series_long_joined_counts <- time_series_long_joined %>% 
  pivot_longer(-c(Province_State, Country_Region, Lat, Long, Date),
               names_to = "Report_Type", values_to = "Counts")
head(time_series_long_joined_counts)
```

## Making a Graph from the Time Series Data
```{r}
time_series_long_joined %>% 
  group_by(Country_Region,Date) %>% 
  summarise_at(c("Confirmed", "Deaths"), sum) %>% 
  filter (Country_Region == "US") %>% 
    ggplot(aes(x = Date,  y = Deaths)) + 
    geom_point() +
    geom_line() +
    ggtitle("US COVID-19 Deaths")
```
```{r}
time_series_long_joined %>% 
  group_by(Country_Region,Date) %>% 
  summarise_at(c("Confirmed", "Deaths"), sum) %>% 
  filter (Country_Region %in% c("China","Japan", "Korea, South",
                                "Italy","Spain", "US")) %>% 
    ggplot(aes(x = Date,  y = Deaths)) + 
    geom_point() +
    geom_line() +
    ggtitle("COVID-19 Deaths") +
    facet_wrap(~Country_Region, ncol=2, scales="free_y")
```
```{r}
time_series_long_joined %>% 
    group_by(Country_Region,Date) %>% 
    summarise_at(c("Confirmed", "Deaths"), sum) %>% 
    filter (Country_Region %in% c("China","France","Italy", 
                                "Korea, South", "US")) %>% 
    ggplot(aes(x = Date,  y = Deaths, color = Country_Region)) + 
    geom_point() +
    geom_line() +
    ggtitle("COVID-19 Deaths")
```
```{r}
time_series_long_joined_counts %>% 
  group_by(Country_Region, Report_Type, Date) %>% 
  summarise(Counts = sum(Counts)) %>% 
  filter (Country_Region == "US") %>% 
    ggplot(aes(x = Date,  y = log2(Counts), fill = Report_Type, color = Report_Type)) + 
    geom_point() +
    geom_line() +
    ggtitle("US COVID-19 Cases")
```

## Exercise 2/3
```{r}
ggplot(Confirmed_State_3_13_9_13_joined_long, aes(x = Confirmed,  y = Province_State))  + 
    geom_bar(stat="identity", fill ="steelblue") +
  labs(title = "US COVID-19 Confirmed Cases",
       x = "Total number of confirmed cases",
       y = "Province or State")
```

## Exercise 4
```{r}
time_series_long_joined_counts %>% 
  group_by(Report_Type, Date) %>% 
  summarise(Counts = sum(Counts)) %>% 
  filter(Report_Type == "Deaths") %>% 
    ggplot(aes(x = Date,  y = Counts)) + 
    geom_point() +
    geom_line() +
    ggtitle("Total Number of Confirmed Deaths Worldwide")+
   labs(x = "Date",
       y = "Confirmed Deaths")
```

## Exercise 5/6
```{r}
time_series_long_joined %>% 
  mutate(deaths_confirmed = Deaths/Confirmed) %>% 
group_by(Country_Region,Date) %>% 
  summarise_at(c("deaths_confirmed"), sum) %>% 
  filter (Country_Region == "US") %>% 
    ggplot(aes(x = Date,  y = deaths_confirmed)) + 
    geom_point() +
    ggtitle("US COVID-19 Deaths/Confirmed")+
  labs(x = "Date",
       y = "Deaths / Confirmed")
```

## Exercise 7
```{r}
time_series_long_joined %>% 
  group_by(Country_Region) %>% 
   summarise(total_deaths= sum(Deaths)) %>% 
    arrange(desc(total_deaths)) %>% 
  slice(1:10)
```
```{r}
time_series_long_joined %>% 
    group_by(Country_Region,Date) %>% 
    summarise_at(c("Confirmed", "Deaths"), sum) %>% 
    filter (Country_Region %in% c("US", "Brazil", "United Kingdom", "Italy", "Mexico", "France", "Spain", "India", "Iran", "Peru")) %>% 
  ggplot(aes(x = Date, y = Deaths, fill = Country_Region, color = Country_Region)) +
  geom_point() +
  geom_line() +
  ggtitle("The Top 10 Countries by Total Deaths") +
  labs(x = "Date",
       y = "Total Deaths")
```

## Exercise 8
```{r}
library(ggthemes)
```
```{r}
time_series_long_joined %>% 
    group_by(Country_Region,Date) %>% 
    summarise_at(c("Confirmed", "Deaths"), sum) %>% 
    filter (Country_Region %in% c("US", "Brazil", "United Kingdom", "Italy", "Mexico", "France", "Spain", "India", "Iran", "Peru")) %>% 
  ggplot(aes(x = Date, y = Deaths, fill = Country_Region, color = Country_Region)) +
  geom_point() +
  geom_line() +
  ggtitle("The Top 10 Countries by Total Deaths") +
  facet_wrap(~Country_Region, ncol=2, scales="free_y")+
    labs(x = "Date",
       y = "Total Deaths")+
    theme_fivethirtyeight()+
   theme(axis.text.x = element_text(color = "black", size = 10), 
         axis.text.y = element_text(color = "black", size = 9), 
         text = element_text(size = 16), 
         axis.title.x = element_text(size = 14, face = "bold"), 
         axis.title.y = element_text(size = 14, face = "bold"), 
         plot.title = element_text(size = 20, face = "bold")) 
```

## Exercise 9
```{r}
time_series_confirmed_US <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv")) 
```
```{r}
time_series_confirmed_US_long <- time_series_confirmed_US %>% 
               pivot_longer(-c(UID, iso2, iso3, code3, FIPS, Admin2,Province_State, Country_Region,Combined_Key, Lat, Long_),
                      names_to = "Date", values_to = "Confirmed") 

time_series_confirmed_US_long$Date <- mdy(time_series_confirmed_US_long$Date)
```
```{r}
time_series_confirmed_US_long %>% 
  group_by(Province_State, Date) %>% 
  summarise(total_confirmed=sum(Confirmed)) %>% 
   ggplot(aes(x = Date,  y = total_confirmed)) + 
    geom_point() +
    geom_line() +
    ggtitle("The Total Confirmed Cases in US") +
    labs(x = "Date",
       y = "Total Confirmed Cases")+
  theme_bw()+
  theme(axis.text.x = element_text(color = "black", size = 15), 
         axis.text.y = element_text(color = "black", size = 15), 
         text = element_text(size = 30), 
         axis.title.x = element_text(size = 40, face = "bold"), 
         axis.title.y = element_text(size = 40, face = "bold"), 
         plot.title = element_text(size = 50, face = "bold")) +
    facet_wrap(~Province_State, ncol=2, scales="free_y")
```

